services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: postgres/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - library-app

  library:
    container_name: library
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - node_modules:/library/node_modules
    networks:
      - library-app
    depends_on:
      - postgres

volumes:
  node_modules:
  postgresql:

networks:
  library-app:
    name: library-app
    driver: bridge
