services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: postgres/Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgresql:/var/lib/postgresql/data
      - postgresql-logs:/var/log/postgresql
    networks:
      - library-app

  library:
    container_name: library
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - ${PORT}:${PORT}
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /usr/app/src
    volumes:
      - node_modules:/library/node_modules
    networks:
      - library-app
    depends_on:
      - postgres

volumes:
  node_modules:
  postgresql:
  postgresql-logs:

networks:
  library-app:
    name: library-app
    driver: bridge
